name: fake_store
description: Consumo del Fake Store API en Dart
version: 1.0.2
repository: https://github.com/jorge-bobrek/fake_store

environment:
  sdk: ^3.3.4

dependencies:
  dartz: ^0.10.1
  http: ^1.2.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
